import { ImageResponse } from "next/og";

export const runtime = "edge";
export const alt = "단백질 제품 비교 — ProteinLab";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// Noto Sans KR Bold subset (Korean + Latin, ~11KB) — embedded to avoid runtime fetch
const FONT_B64 =
  "AAEAAAASAQAABAAgR0RFRgATAEoAAAE8AAAAFkdQT1M/N0FfAAAJdAAAA3RHU1VCj+p71AAAAqAAAAB+T1MvMpQXLWIAAAJAAAAAYFNUQVR5oGtJAAAB3AAAACpjbWFwUBH6rAAABYgAAAGMZ2FzcAAAABAAAAE0AAAACGdseWa8X1CWAAAM6AAAHX5oZWFkItUf5QAAAggAAAA2aGhlYQwECJ0AAAGUAAAAJGhtdHim4hA2AAAEWAAAATBsb2NhC34EGgAAAyAAAACabWF4cACKAeAAAAFUAAAAIG5hbWUw0VCBAAAHFAAAAl5wb3N0/4YAMgAAAXQAAAAgcHJlcGgGjIUAAAEsAAAAB3ZoZWEMahcDAAABuAAAACR2bXR4C8AMBQAAA7wAAACauAH/hbAEjQAAAQAB//8ADwABAAAADAAAAAAAAAABAEcAAgADAAMAAAABAAAATAHfAD0AAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAD/gwAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABIj+4AAAC7j8C/24C24AAQAAAAAAAAAAAAAAAAAAAEwAARAAAfT+DAAAC7j/BP0+C24AAAABAAAAAAAAAAAAAAAAAAEAAQABAAgAAQAAABQAAQAAABwAAndnaHQBAQAAAAIAAQAAAAABEAK8AAAAAAABAAAAAgEGwFekIF8PPPUAAwPoAAAAANywIy4AAAAA35K31vwL++oLbgcOAAEABgACAAAAAAAAAAQDtAK8AAUAAAKKAlgAAABLAooCWAAAAV4AMgFFAAACCwIAAAAAAAAAMAAAgyvfPBAAAAAWAAAAAEFEQk8AIAAgHr0DcP+IAAAEiAEgYC4BBwAAAAACHwLdAAAAIAAGAAEAAAAKAFIAYAAHREZMVAA+Y3lybAAsZ3JlawAsaGFuZwAsaGFuaQAsa2FuYQAsbGF0bgAsAAAAAUtPUiAACgAA//8AAQAAAAQAAAAA//8AAAABbG9jbAAIAAAAAQAAAAEABAABAAAAAQAIAAIACgACAEoASwABAAIAAQAYAAAAAAArACsATQB+AIoAmQC8AOIBHwFWAY4BqgHMAf8CHwJFAmcCewLaAykDVQNyA64DvAPTA+cEEwRRBI0EtwThBSQFZgWoBc8GFwYrBj8GagaYBsYHCwdPB5MH8whPCKsI6gkpCYAJlAmoCdMKGApSCowK4gs0C14LiAvJC/YMJQxODJUM2g0nDXANvQ4GDi8OPw5ODqkOqQ6/AAAD6AAAA3AAiwB+AIsAiwCLAIsBMgBSATIARQEyATIBMgCpAUAAHQCJAEUAZgBE//j/1AGcAAUARAB+ATL/gv+C/63/v/9+AIsAfv+C/4L/v/+C/4L/v//U/9QALwBQAAv/1P/UAFD/1P/UAFAAL//U/9QALwBQ/9T/1ABQ/60AL//U/60AL/8E/5T/BP+U/9QAigB/AC8DcAGUAAAD6ABkAOMAAAKB//wCkAA2AUoAWwJCAFsCmwBbAuwAWAJPADMChABPAkUALAEwAEQCgQBPAnIALAG1AE8BpQAVAn0ASQEoAGQDUQA1AgEAIgGUACwD6ACRAagAIgJyAPQCUADLAagAWgGkABwDtAA6AgIAMQKB//wCgf/8AoH//AKB//wCgf/8A7f/9wKQADYBSv/uAUoAVwFK/+MC7ABYAuwAWALsAFgCTwAzAk8AMwJPADMCTwAzAk8AMwJFACwCRQAsAkUALAEw/84BMABPATD/1gKBAE8CcgAsAnIALAJyACwCcgAsAn0ASQJ9AEkCfQBJAUr/zQEw/8YCgQBPAuwAWAJ9AEkC7ABYAn0ASQLsAFgCfQBJAoEATwAAAGIAAABhAkUALAEYAAABRgBHAAAAAgAAAAMAAAAUAAMAAQAAABQABAF4AAAAWgBAAAUAGgAgAEEAQwBJAEwAUABVAGIAZQBpAG8AcgB1AKYAqQCuALEAtAC3ALoAvQDBAMcAzQDPANoA3ADhAOUA6QDtAO8A8wD2APoA/AEpAUQBaQHYAdwB+QMBHr3//wAAACAAQQBDAEkATABQAFUAYQBlAGkAbgByAHQApgCpAK4AsACzALcAuQC9AL8AwwDMAM8A2QDcAOAA4wDoAOsA7wDxAPUA+QD8ASgBRAFoAdcB2wH5AwAevf///+H/wf/A/7v/uf+2/7L/p/+l/6L/nv+c/5v/a/9p/2X/ZP9j/2H/YP9e/13/XP9Y/1f/Tv9N/0r/Sf9H/0b/Rf9E/0P/Qf9A/xX++/7Y/mv+af5N/UfhjAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgB+AAMAAQQJAAAAnAFEAAMAAQQJAAEAGAEsAAMAAQQJAAIACAEkAAMAAQQJAAMAOgDqAAMAAQQJAAQAIgDIAAMAAQQJAAUAagBeAAMAAQQJAAYAHgBAAAMAAQQJAA4ANAAMAAMAAQQJAQEADAAAAAMAAQQJARAACAEkAFcAZQBpAGcAaAB0AGgAdAB0AHAAOgAvAC8AcwBjAHIAaQBwAHQAcwAuAHMAaQBsAC4AbwByAGcALwBPAEYATABOAG8AdABvAFMAYQBuAHMASwBSAC0AQgBvAGwAZABWAGUAcgBzAGkAbwBuACAAMgAuADAAMAA0AC0ASAAyADsAaABvAHQAYwBvAG4AdgAgADEALgAwAC4AMQAxADgAOwBtAGEAawBlAG8AdABmAGUAeABlACAAMgAuADUALgA2ADUANgAwADMATgBvAHQAbwAgAFMAYQBuAHMAIABLAFIAIABCAG8AbABkADIALgAwADAANAAtAEgAMgA7AEEARABCAE8AOwBOAG8AdABvAFMAYQBuAHMASwBSAC0AQgBvAGwAZABCAG8AbABkAE4AbwB0AG8AIABTAGEAbgBzACAASwBSACgAYwApACAAMgAwADEANAAtADIAMAAyADEAIABBAGQAbwBiAGUAIAAoAGgAdAB0AHAAOgAvAC8AdwB3AHcALgBhAGQAbwBiAGUALgBjAG8AbQAvACkALAAgAHcAaQB0AGgAIABSAGUAcwBlAHIAdgBlAGQAIABGAG8AbgB0ACAATgBhAG0AZQAgACcAUwBvAHUAcgBjAGUAJwAuAAAAAQAAAAoAQgBQAAdERkxUACxjeXJsACxncmVrACxoYW5nACxoYW5pACxrYW5hACxsYXRuACwABAAAAAD//wABAAAAAWtlcm4ACAAAAAEAAAABAAQAAgAAAAEACAACAbQABAAAAoQB7gAPAA4AAAAA/+8ADf/4/+v/+AAAAAD/5/+U/9wAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+cAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAP/f/+sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7wAAAAAAAAAAAAAAAAAA/9wAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAP/v/+7/8gAAAAAAAAAAAAD/8v/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/1AAAAAD/5//vAAAAAP/U//n/rwAAAAAAAP/s/9UAAP/2/9T/7wAAAAD/3f+C/4IAAAAAAAD/4QAA/9L/wgAAAAAAAAAAAAAAEf/4AAAAAAAA/+8AAP/c/+cAAAAAAAAAAAAAACn/7AAAAAAAAP/nAAD/4wAAAAAAAAAAAAD/5AAZ/+QAAAAAAAAAAAAAAAD/3AAAAAAAAAAAAAAAAAAAAAAAAAAA/9f/rP/F/6D/wgAAAAAAAAAAAAAAAAAAAAAAAgAJAAIAAwAAAAUACgACAAwAEAAIABgAGAANABwAIwAOACcAMQAWADUAPAAhAD8ARgApAEkASQAxAAEAAgBIAAQAAgAAAAAAAAAFAAMAAAABAAcACAABAAgACQAGAAAAAAAKAAAAAAAAAAAACwAAAAAAAAAMAAQABAAEAAQABAANAAIAAAAAAAAABQAFAAUAAwADAAMAAwADAAEAAQABAAcABwAHAAgAAQABAAEAAQAGAAYABgAAAAcACAAFAAYABQAGAAUABgAIAAAAAAABAAEAAwBHAAgAAAAJAAoABgABAAIABQAAAAcAAgALAAwAAwAAAAAAAAAAAAAAAAAAAA0AAAAAAAAADgAAAAAAAAAAAAAABAAIAAAAAAAAAAYABgAGAAEAAQABAAEAAQAFAAUABQAAAAAAAAAHAAIAAgACAAIAAwADAAMAAAAAAAcABgADAAYAAwAGAAMABwAAAAAABQAFAGT/iAOEA3AAAwAGAAkADAAPAAAXESERAQEhAQERASEBAREBZAMg/nABPv2EAV4BPv1kAnz+wv6iAT54A+j8GAIdAZn+Pv5nAzL8pQGZAcL8zgGZAAL//AAAAoUC5QANABEAACMTMxMjAyYmJyMGBgcDJzUhFQTtr+2caREfEQQOIRBqAwFgAuX9GwGCOn07PHw6/n6+c3MAAQA2//ICdQLyAB8AAAUiLgI1ND4CMzIWFwcmJiMiBgYVFBYWMzI2NxcGBgGIRnpdNTZffUZHbyNNHEMqOFkyL1c6MEsdTy52DjFijlxcj2Q0OSZeHCI9clBRcz4pIFw2NwABAFsAAADvAuUAAwAAMxEzEVuUAuX9GwABAFsAAAIcAuUABQAAMxEzESEVW5QBLQLl/Zd8AAACAFsAAAJwAuUADAAVAAAzETMyFhYVFAYGIyMRETMyNjU0JiMjW/NSg01NgVBjWUxLT01UAuUsZVhUbTT++QF8QEBAMwAAAQBY//IClQLlABcAAAUiLgI1ETMRFBYWMzI2NjURMxEUDgIBeEVqSyaTIj8sLEAjjiZKag4nVIRcAZj+W01aJydaTQGl/mhchFQnAAIAM//yAggCPgAdACgAABciJiY1NDY3LgIjIgYHJz4CMzIWFhURIycjBgY1MjY3NQ4CFRQW2DFLKZqoARIpIydMJzQhSlIsR2AweAoFJFQfMxpEUCIpDitMMFljEhwrGh4YYhUgFThuUf65PCAqcx0acAgeKRkhHgAAAgBP//ICVgMeABQAIwAABSImJyMHIxEzFQc2NjMyFhYVFAYGJzI2NjU0JiYjIgYHFRYWAWglTiIFDHOTBSJRKUVjNURtXSE2IBgwJxw1HRo1DiYjOwMeyVoeJUd/VmCJR3knUD01SyYcHfcYEgACACz/8gIbAj4AGwAjAAAFIiYmNTQ+AjMyFhYVFAYHIR4CMzI2NxcGBgMzNCYjIgYGAUNOfksrS10yTWg1BAP+pwYqQioiPB8yKWa/5TM3HTQkDkaEXERsTSlFeU4UJQstPh8TE1ocIgFfOEMbNwAAAgBEAAAA7gMrAAMADwAAMxEzEQMiJjU0NjMyFhUUBk+TSScuLiclMDACMP3QAosrJSQsLCQlKwABAE8AAAI4Aj4AFAAAMxEzFzM2NjMyFhURIxE0JiMiBgcRT3gLAyVYOVtSkyUqIjMfAjBKJDR3av6jAUtBNCAf/n8AAAIALP/yAkYCPgAQACAAAAUiJiY1NDY2MzIeAhUUBgYnMjY2NTQmJiMiBgYVFBYWATlGe0xMe0Y1YEwsTHtGJjUbGzUmJjUbGzUORoNdXYNGKEttRl2DRngrTjU1TisrTjU1TisAAAEATwAAAbUCPgASAAAzETMXMzY2MzIWFwcmJiMiBgcRT3gLAx9ULBgdDBgQGRMgRxgCMGM3OgcFfwQFMjz+sgABABX/8gGTAscAGAAABSImJjU1IzU3NzMVMxUjFRQWMzI2NxcGBgEcQlIkT1cReYuLKCUOHgsZFzsONV4++W0Hl5d0+DAuCARrBw4AAQBJ//ICLwIwABQAABciJjURMxEUFjMyNjcRMxEjJyMGBvZbUpImKiIzHJN4CwQkVA53agFd/rVBNCElAXr90FErNAACAGT+5ADEA1MAAwAHAAATETMRAxEzEWRgYGABWwH4/gj9iQIH/fkAAwA1//YDHALnABMAJwBDAAAFIi4CNTQ+AjMyHgIVFA4CJzI+AjU0LgIjIg4CFRQeAjciJiY1NDY2MzIWFwcmJiMiBhUUFjMyNjcXBgYBqEuGZzs7Z4ZLS4dnOztnh0s/blMuLlNuPz9tUy4uU21MPmI4PWM5M0YbOBQmGTg+PDQfLBcwIEgKNGOMV1iKYjMzYopYV4xjND8tVHNHR3NSLCxSc0dHc1QtWzZkRUNhNicbQBQVSjc+SRcSRRoiAAQAIgFkAd0DKwAPAB8ALQA2AAABIiYmNTQ2NjMyFhYVFAYGJzI2NjU0JiYjIgYGFRQWFic1MzIWFRQGBxcjJyMVNTMyNjU0JiMjAQA9ZTw8ZT09ZDw8ZD0wSisrSjAwSisrSilhJjUWEzA/JCQYExQRFBoBZDpnQkNnOjpnQ0JnOjMsTzU1TywsTzU1TyxB4iQnEyIIWkhIchMODxEAAgAsAc0BaAMKAA8AGwAAEyImJjU0NjYzMhYWFRQGBicyNjU0JiMiBhUUFssrSSsrSSssRisrRiwjKysjIywsAc0pRy4vRykpRy8uRylIMCYnLy8nJjAAAAIAkQAJA18DLAALAA8AAAEhFSM1ITUhNTMVIRMVITUDV/7QZv7QATBmATAI/TIByv39Zf39/kBmZgABACIBogF5A3gAKAAAEyImJzcWFjMyNjU0JiM1MjY1NCYjIgYHJzY2MzIWFhUUBgcWFhUUBgbROFscQxQwHh4pOTouNCIcFicQPiJJMilEKiUfIzIuTQGiLyo0HB0fHCEfQCAeGR0bFTgmJR03JiQyEg03KCg+IgABAPQCigIDA5wAAwAAASc3FwE9SatkAopHy2EAAQDLARQBggHUAAsAAAEiJjU0NjMyFhUUBgEnKDQ0KCY1NQEUOCgpNzcpKDgAAAEAWgGvASsDawAIAAATESM1NjY3MxG9Yys0G1cBrwFIQwcXE/5EAAACABwBpgGHAywADwAbAAATIiYmNTQ2NjMyFhYVFAYGJzI2NTQmIyIGFRQW0jBTMzNTMDBSMzNSMCUkJCUlJSUBpi9XPD5YLi5YPjxXL1Q9MTM+PjMxPQAAAwA6//IDgwLyAAgADAAlAAATESM1NjY3MxEDATMBJTU+AjU0JiMiBgcnNjYzMhYVFAYGBzMVnmQrNBtWTAGSWP5tASs9WDImIBgqEz4fUzFHWCM7JJUBKwFGRAcWE/5G/scDAP0ADjwyU0QdJCgfGjksLk1HJUdGJlwAAAIAMf8qAdQCPgAbACcAAAUiJiY1ND4DJzMWDgMVFBYWMzI2NxcGBgMiJjU0NjMyFhUUBgECPF82IzMwHgWBBxotMCIVJhohNhdSJ2ozJzQ0Jyg0NNYqVUArQTo5QSowSz42NB0ZJRQgGEotOAJUNygqNzcqKDcAAAP//AAAAoUD7gANABEAFQAAIxMzEyMDJiYnIwYGBwMnNSEVAyc3FwTtr+2caREfEQQOIRBqAwFgosdPuQLl/RsBgjp9Ozx8Ov5+vnNzAkuFYJsAAAP//AAAAoUD7gANABEAFQAAIxMzEyMDJiYnIwYGBwMnNSEVAyc3FwTtr+2caREfEQQOIRBqAwFgvkG5TgLl/RsBgjp9Ozx8Ov5+vnNzAktKm2AAAAP//AAAAoUDwwANABEAKQAAIxMzEyMDJiYnIwYGBwMnNSEVAyIuAiMiBgcnNjYzMh4CMzI2NxcGBgTtr+2caREfEQQOIRBqAwFgXh4vJB4QEhgEXwVKOR4vJB8PEhcEYARLAuX9GwGCOn07PHw6/n6+c3MCWRUbFRwhCFBMFRsVHCEHUUwABP/8AAAChQOxAA0AEQAdACkAACMTMxMjAyYmJyMGBgcDJzUhFQEiJjU0NjMyFhUUBjMiJjU0NjMyFhUUBgTtr+2caREfEQQOIRBqAwFg/tQfKSkfICkp1yApKSAgKSkC5f0bAYI6fTs8fDr+fr5zcwJhKSAfKiofICkpIB8qKh8gKQAABP/8AAAChQPyAA0AEQAdACkAACMTMxMjAyYmJyMGBgcDJzUhFQMiJjU0NjMyFhUUBicyNjU0JiMiBhUUFgTtr+2caREfEQQOIRBqAwFgsDdERDc2RkY2FR0dFRUdHQLl/RsBgjp9Ozx8Ov5+vnNzAlg9MTM7OzMxPTocGBkdHRkYHAAAAv/3AAADfgLlABIAFgAAIwEhFSEVMxUjFSEVIREjBgYHAzc1IRUJAWoCEv7c9fUBL/48BBkxGcERAWcC5XyrfMZ8AnU4cDP+ZrZzcwAAAgA2/vQCdQLyAB8ALwAABSIuAjU0PgIzMhYXByYmIyIGBhUUFhYzMjY3FwYGByc2NjU0Jic3MwcWFhUUBgGIRnpdNTZffUZHbyNNHEMqOFkyL1c6MEsdTy52tQxEMiQzNlchKixwDjFijlxcj2Q0OSZeHCI9clBRcz4pIFw2N/4+BBcZEhkHbEoJJyM4NwAAAv/uAAAA9QPuAAMABwAAMxEzEQMnNxdblDvGT7gC5f0bAwmFYJsAAAIAVwAAAV8D7gADAAcAADMRMxEDJzcXW5RXQbpOAuX9GwMJSptgAAAD/+MAAAFrA7EAAwAPABsAADMRMxEDIiY1NDYzMhYVFAYzIiY1NDYzMhYVFAZblMQgKCggISkp1SAoKCAhKSkC5f0bAx8pIB8qKh8gKSkgHyoqHyApAAIAWP/yApUD7gAXABsAAAUiLgI1ETMRFBYWMzI2NjURMxEUDgIDJzcXAXhFaksmkyI/LCxAI44mSmo3x0+4DidUhFwBmP5bTVonJ1pNAaX+aFyEVCcDF4VgmwAAAgBY//IClQPuABcAGwAABSIuAjURMxEUFhYzMjY2NREzERQOAgMnNxcBeEVqSyaTIj8sLEAjjiZKalRAuFAOJ1SEXAGY/ltNWicnWk0Bpf5oXIRUJwMXSptgAAADAFj/8gKVA7EAFwAjAC8AAAUiLgI1ETMRFBYWMzI2NjURMxEUDgIDIiY1NDYzMhYVFAYzIiY1NDYzMhYVFAYBeEVqSyaTIj8sLEAjjiZKasEgKCggISkp1iAoKCAgKCgOJ1SEXAGY/ltNWicnWk0Bpf5oXIRUJwMtKSAfKiofICkpIB8qKh8gKQADADP/8gIIA5wAHQAoACwAABciJiY1NDY3LgIjIgYHJz4CMzIWFhURIycjBgY1MjY3NQ4CFRQWEyc3F9gxSymaqAESKSMnTCc0IUpSLEdgMHgKBSRUHzMaRFAiKUvGZKsOK0wwWWMSHCsaHhhiFSAVOG5R/rk8ICpzHRpwCB4pGSEeAiWxYcsAAwAz//ICCAOcAB0AKAAsAAAXIiYmNTQ2Ny4CIyIGByc+AjMyFhYVESMnIwYGNTI2NzUOAhUUFhMnNxfYMUspmqgBEikjJ0wnNCFKUixHYDB4CgUkVB8zGkRQIilTSaplDitMMFljEhwrGh4YYhUgFThuUf65PCAqcx0acAgeKRkhHgIlR8thAAMAM//yAgkDQQAdACgAQgAAFyImJjU0NjcuAiMiBgcnPgIzMhYWFREjJyMGBjUyNjc1DgIVFBYTIi4CIyIGByc+AjMyHgIzMjY3Fw4C2DFLKZqoARIpIydMJzQhSlIsR2AweAoFJFQfMxpEUCIpnBwqIx8PExUDXQIeOiocLCMeDxQUA10BHzoOK0wwWWMSHCsaHhhiFSAVOG5R/rk8ICpzHRpwCB4pGSEeAicYHhgiJAY2SyYYHxciIgQ2SyYAAAQAM//yAggDIAAdACgANABAAAAXIiYmNTQ2Ny4CIyIGByc+AjMyFhYVESMnIwYGNTI2NzUOAhUUFgMiJjU0NjMyFhUUBjMiJjU0NjMyFhUUBtgxSymaqAESKSMnTCc0IUpSLEdgMHgKBSRUHzMaRFAiKSkgKiogISkpziAqKiAhKioOK0wwWWMSHCsaHhhiFSAVOG5R/rk8ICpzHRpwCB4pGSEeAiYsHiArKyAeLCweICsrIB4sAAAEADP/8gIIA2UAHQAoADQAQAAAFyImJjU0NjcuAiMiBgcnPgIzMhYWFREjJyMGBjUyNjc1DgIVFBYTIiY1NDYzMhYVFAYnMjY1NCYjIgYVFBbYMUspmqgBEikjJ0wnNCFKUixHYDB4CgUkVB8zGkRQIilPRUlJRUZISEYXHh4XFSEhDitMMFljEhwrGh4YYhUgFThuUf65PCAqcx0acAgeKRkhHgIYQzExQ0MxMUM5IBsbISEbGyAAAwAs//ICGwOcABsAIwAnAAAFIiYmNTQ+AjMyFhYVFAYHIR4CMzI2NxcGBgMzNCYjIgYGEyc3FwFDTn5LK0tdMk1oNQQD/qcGKkIqIjwfMilmv+UzNx00JG3GZKoORoRcRGxNKUV5ThQlCy0+HxMTWhwiAV84Qxs3ARCxYcsAAwAs//ICGwOcABsAIwAnAAAFIiYmNTQ+AjMyFhYVFAYHIR4CMzI2NxcGBgMzNCYjIgYGEyc3FwFDTn5LK0tdMk1oNQQD/qcGKkIqIjwfMilmv+UzNx00JHZKq2QORoRcRGxNKUV5ThQlCy0+HxMTWhwiAV84Qxs3ARBHy2EABAAs//ICGwMgABsAIwAvADsAAAUiJiY1ND4CMzIWFhUUBgchHgIzMjY3FwYGAzM0JiMiBgYDIiY1NDYzMhYVFAYzIiY1NDYzMhYVFAYBQ05+SytLXTJNaDUEA/6nBipCKiI8HzIpZr/lMzcdNCQIICoqICErK9AgKysgICsrDkaEXERsTSlFeU4UJQstPh8TE1ocIgFfOEMbNwERLB4gKysgHiwsHiArKyAeLAAAAv/OAAAA4gOcAAMABwAAMxEzEQMnNxdPk03HZaoCMP3QAoqxYcsAAAIATwAAAWMDnAADAAcAADMRMxEDJzcXT5NFSaplAjD90AKKR8thAAAD/9YAAAFbAyAAAwAPABsAADMRMxEDIiY1NDYzMhYVFAYzIiY1NDYzMhYVFAZPk8EhKiohISkpzyArKyAgKioCMP3QAossHx8rLB4fLCwfHyssHh8sAAIATwAAAjgDQQAUAC4AADMRMxczNjYzMhYVESMRNCYjIgYHERMiLgIjIgYHJz4CMzIeAjMyNjcXDgJPeAsDJVg5W1KTJSoiMx/JHCsjHhATFQJdAR47KxsrIx8PExQEXAEfOQIwSiQ0d2r+owFLQTQgH/5/AowYHhgiJAY2SyYYHxciIgQ2SyYAAAMALP/yAkYDnAAQACAAJAAABSImJjU0NjYzMh4CFRQGBicyNjY1NCYmIyIGBhUUFhYTJzcXATlGe0xMe0Y1YEwsTHtGJjUbGzUmJjUbGzUixmSqDkaDXV2DRihLbUZdg0Z4K041NU4rK041NU4rAiCxYcsAAwAs//ICRgOcABAAIAAkAAAFIiYmNTQ2NjMyHgIVFAYGJzI2NjU0JiYjIgYGFRQWFhMnNxcBOUZ7TEx7RjVgTCxMe0YmNRsbNSYmNRsbNSpJq2QORoNdXYNGKEttRl2DRngrTjU1TisrTjU1TisCIEfLYQADACz/8gJGA0EAEAAgADoAAAUiJiY1NDY2MzIeAhUUBgYnMjY2NTQmJiMiBgYVFBYWEyIuAiMiBgcnPgIzMh4CMzI2NxcOAgE5RntMTHtGNWBMLEx7RiY1Gxs1JiY1Gxs1cxwqIx8QEhUDXQIeOyocKyMeEBIVBFwBHzoORoNdXYNGKEttRl2DRngrTjU1TisrTjU1TisCIhgeGCIkBjZLJhgfFyIiBDZLJgAABAAs//ICRgMgABAAIAAsADgAAAUiJiY1NDY2MzIeAhUUBgYnMjY2NTQmJiMiBgYVFBYWAyImNTQ2MzIWFRQGMyImNTQ2MzIWFRQGATlGe0xMe0Y1YEwsTHtGJjUbGzUmJjUbGzVSICoqICEqKs4gKiogISoqDkaDXV2DRihLbUZdg0Z4K041NU4rK041NU4rAiEsHiArKyAeLCweICsrIB4sAAACAEn/8gIvA5wAFAAYAAAXIiY1ETMRFBYzMjY3ETMRIycjBgYTJzcX9ltSkiYqIjMck3gLBCRUCsVkqg53agFd/rVBNCElAXr90FErNAKYsWHLAAACAEn/8gIvA5wAFAAYAAAXIiY1ETMRFBYzMjY3ETMRIycjBgYTJzcX9ltSkiYqIjMck3gLBCRUFEqrZA53agFd/rVBNCElAXr90FErNAKYR8thAAADAEn/8gIvAyAAFAAgACwAABciJjURMxEUFjMyNjcRMxEjJyMGBgMiJjU0NjMyFhUUBjMiJjU0NjMyFhUUBvZbUpImKiIzHJN4CwQkVGkgKiogISkpzyAqKiAhKSkOd2oBXf61QTQhJQF6/dBRKzQCmSweICsrIB4sLB4gKysgHiwAAv/NAAABgQPDAAMAGwAAMxEzERMiLgIjIgYHJzY2MzIeAjMyNjcXBgZblAofLiMgEBEZA18ESzkfLSQfEBIXBGAFSgLl/RsDFxUbFRwhCFBMFRsVHCEHUUwAAv/GAAABagNBAAMAHQAAMxEzERMiLgIjIgYHJz4CMzIeAjMyNjcXDgJPkwMcKiMeDxQVAl4DHjorGysjHw8TFQJdAR86AjD90AKMGB4YIiQGNksmGB8XIiIENksmAAIATwAAAjgDnAAUABgAADMRMxczNjYzMhYVESMRNCYjIgYHERMnNxdPeAsDJVg5W1KTJSoiMx+ASapkAjBKJDR3av6jAUtBNCAf/n8CikfLYQACAFj/8gKVA8MAFwAvAAAFIi4CNREzERQWFjMyNjY1ETMRFA4CEyIuAiMiBgcnNjYzMh4CMzI2NxcGBgF4RWpLJpMiPywsQCOOJkpqDR8vIx8PEhgEXwRLOB8uJR8PERgFXwVLDidUhFwBmP5bTVonJ1pNAaX+aFyEVCcDJRUbFRwhCFBMFRsVHCEHUUwAAgBJ//ICLwNBABQALgAAFyImNREzERQWMzI2NxEzESMnIwYGEyIuAiMiBgcnPgIzMh4CMzI2NxcOAvZbUpImKiIzHJN4CwQkVFwcKyMfDhQUA14CHzsqHCojHw8UFANdAh85DndqAV3+tUE0ISUBev3QUSs0ApoYHhgiJAY2SyYYHxciIgQ2SyYABABY//IClQRsABcAIwAnADMAAAUiLgI1ETMRFBYWMzI2NjURMxEUDgIDIiY1NDYzMhYVFAY3JzcXAyImNTQ2MzIWFRQGAXhFaksmkyI/LCxAI44mSmrBHCUlHB0lJWVAbVsTHCUlHB0kJA4nVIRcAZj+W01aJydaTQGl/mhchFQnAy0lHBwlJRwcJYgpnDr+7SUcHCUlHBwlAAQASf/yAi8D3AAUACAAJAAwAAAXIiY1ETMRFBYzMjY3ETMRIycjBgYDIiY1NDYzMhYVFAY3JzcXEyImNTQ2MzIWFRQG9ltSkiYqIjMck3gLBCRUaRwlJRwcJiZfOFlPBRwmJhwcJSUOd2oBXf61QTQhJQF6/dBRKzQCmyUbHSQkHRslmSWRNP7lJRsdJCQdGyUABABY//IClQRsABcAIwAnADMAAAUiLgI1ETMRFBYWMzI2NjURMxEUDgIDIiY1NDYzMhYVFAY3JzcXFyImNTQ2MzIWFRQGAXhFaksmkyI/LCxAI44mSmrBHCUlHB0lJViIXG1BHCUlHB0kJA4nVIRcAZj+W01aJydaTQGl/mhchFQnAy0lHBwlJRwcJYiLOpyxJRwcJSUcHCUAAAQASf/yAi8D3AAUACAAJAAwAAAXIiY1ETMRFBYzMjY3ETMRIycjBgYDIiY1NDYzMhYVFAY3JzcXFyImNTQ2MzIWFRQG9ltSkiYqIjMck3gLBCRUaRwlJRwcJiZYcFBZQxwmJhwcJSUOd2oBXf61QTQhJQF6/dBRKzQCmyUbHSQkHRslmYI0kb4lGx0kJB0bJQAAAgBPAAACOAOcABQAGAAAMxEzFzM2NjMyFhURIxE0JiMiBgcREyc3F094CwMlWDlbUpMlKiIzH3fFZKoCMEokNHdq/qMBS0E0IB/+fwKKsWHLAAEAYgFbAf8C5gADAAABAQcBAf/+xmMBUQGoAT5f/tQAAQBhAWAB9wLxAAMAAAEnARcB90L+rGECpUz+1mcAAwAs//ICGwNBABsAIwA9AAAFIiYmNTQ+AjMyFhYVFAYHIR4CMzI2NxcGBgMzNCYjIgYGEyIuAiMiBgcnPgIzMh4CMzI2NxcOAgFDTn5LK0tdMk1oNQQD/qcGKkIqIjwfMilmv+UzNx00JL4cKyMeDxMVA10BHzsqHCsjHhATFANdAR87DkaEXERsTSlFeU4UJQstPh8TE1ocIgFfOEMbNwESGB4YIiQGNksmGB8XIiIENksmAAABAEcBHQD/AdwACwAAEyImNTQ2MzIWFRQGoyg0NCgnNTUBHTYpKjY2Kik2AAA=";

function b64ToBuffer(b64: string): ArrayBuffer {
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  return buf.buffer;
}

export default async function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "1200px",
          height: "630px",
          background: "linear-gradient(145deg, #0c2218 0%, #163828 55%, #0f2a1e 100%)",
          display: "flex",
          flexDirection: "column",
          position: "relative",
          overflow: "hidden",
          fontFamily: "'Noto Sans KR', sans-serif",
        }}
      >
        {/* Decorative background circles */}
        <div style={{ position: "absolute", top: "-120px", right: "-80px", width: "500px", height: "500px", borderRadius: "50%", background: "rgba(74,180,120,0.08)", display: "flex" }} />
        <div style={{ position: "absolute", bottom: "-140px", left: "-60px", width: "400px", height: "400px", borderRadius: "50%", background: "rgba(74,180,120,0.06)", display: "flex" }} />

        {/* Top badge */}
        <div style={{ position: "absolute", top: "48px", left: "64px", display: "flex" }}>
          <div style={{ background: "rgba(74,180,120,0.18)", border: "1px solid rgba(74,180,120,0.4)", borderRadius: "24px", padding: "6px 18px", display: "flex" }}>
            <span style={{ color: "#6de0a0", fontSize: "15px", fontWeight: 700, letterSpacing: "0.08em" }}>
              PROTEIN COMPARISON PLATFORM
            </span>
          </div>
        </div>

        {/* Main content — left column */}
        <div style={{ display: "flex", flexDirection: "column", position: "absolute", left: "64px", top: "118px" }}>
          {/* Logo row */}
          <div style={{ display: "flex", alignItems: "center", gap: "16px" }}>
            <div style={{ width: "64px", height: "64px", background: "linear-gradient(135deg, #2db872 0%, #1a8c52 100%)", borderRadius: "18px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "36px" }}>
              💪
            </div>
            <span style={{ fontSize: "52px", fontWeight: 700, color: "#ffffff", letterSpacing: "-0.01em" }}>
              ProteinLab
            </span>
          </div>

          {/* Tagline */}
          <div style={{ marginTop: "22px", fontSize: "28px", fontWeight: 700, color: "rgba(255,255,255,0.88)", display: "flex" }}>
            단백질 음료 · 바 · 요거트 · 쉐이크
          </div>
          <div style={{ marginTop: "8px", fontSize: "22px", fontWeight: 700, color: "rgba(74,200,130,0.9)", display: "flex" }}>
            함량 · 칼로리 · 당류 기준 비교
          </div>

          {/* Category pills */}
          <div style={{ display: "flex", gap: "10px", marginTop: "40px" }}>
            {[
              { label: "🥤 음료", count: "110" },
              { label: "🍫 바", count: "100" },
              { label: "🥣 요거트", count: "57" },
              { label: "🥛 쉐이크", count: "88" },
            ].map((cat) => (
              <div key={cat.label} style={{ display: "flex", alignItems: "center", gap: "6px", background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.15)", borderRadius: "40px", padding: "8px 18px" }}>
                <span style={{ color: "rgba(255,255,255,0.9)", fontSize: "16px", fontWeight: 700 }}>{cat.label}</span>
                <span style={{ background: "rgba(74,180,120,0.25)", color: "#6de0a0", borderRadius: "20px", padding: "1px 8px", fontSize: "13px", fontWeight: 700 }}>{cat.count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Right side stat cards */}
        <div style={{ display: "flex", flexDirection: "column", gap: "14px", position: "absolute", right: "64px", top: "118px" }}>
          {[
            { label: "단백질", value: "25g", color: "#4ac882" },
            { label: "칼로리", value: "130kcal", color: "#72b8e8" },
            { label: "당류", value: "0g", color: "#f0b84a" },
          ].map((stat) => (
            <div key={stat.label} style={{ width: "220px", background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.12)", borderRadius: "16px", padding: "16px 20px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <span style={{ color: "rgba(255,255,255,0.65)", fontSize: "16px", fontWeight: 700 }}>{stat.label}</span>
              <span style={{ color: stat.color, fontSize: "22px", fontWeight: 700 }}>{stat.value}</span>
            </div>
          ))}
          <div style={{ width: "220px", background: "linear-gradient(135deg, rgba(45,184,114,0.2) 0%, rgba(26,140,82,0.2) 100%)", border: "1px solid rgba(74,180,120,0.35)", borderRadius: "16px", padding: "16px 20px", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <span style={{ color: "#6de0a0", fontSize: "15px", fontWeight: 700 }}>proteinlab.kr</span>
          </div>
        </div>

        {/* Bottom accent line */}
        <div style={{ position: "absolute", bottom: "0", left: "0", right: "0", height: "4px", background: "linear-gradient(90deg, #1a8c52 0%, #2db872 50%, #1a8c52 100%)", display: "flex" }} />
      </div>
    ),
    {
      ...size,
      fonts: [{ name: "Noto Sans KR", data: b64ToBuffer(FONT_B64), weight: 700, style: "normal" }],
    },
  );
}
